#!/bin/bash -e

cat <<YAML
steps:
  - name: Run Unit Tests
    command: 'build-and-deploy/unit_tests'
    agents:
      queue: muppets:build
YAML

if test "$BUILDKITE_BRANCH" = "master" && test "$BUILDKITE_PULL_REQUEST" = "false"; then
cat <<YAML
  - name: Docker Publish
    command: 'build-and-deploy/docker_publish'
    branches: "master"
    agents:
      queue: muppets:build
  - wait
  - name: Deploy to Prod
    branches: "master"
    command: 'build-and-deploy/deploy'
    agents:
      queue: muppets:build
YAML
fi